name: mmybrand CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
  
      - name: Install dependencies
        run: npm install

      - name: setting environment variable
        run: |
          echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> $GITHUB_ENV
          echo "RESET=${{secrets.RESET}}" >> $GITHUB_ENV
          echo "TOKEN_EXPIRE=${{secrets.TOKEN_EXPIRE}}" >> $GITHUB_ENV
          echo "RESETEXP=${{secrets.RESETEXP}}" >> $GITHUB_ENV


      - name: Run tests
        run: npm test
